# MNIST

In [2]:
import tensorflow as tf

In [9]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train, x_test = x_train / 255.0, x_test / 255.0


In [10]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [11]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.21178134,  0.40420696,  0.78570473, -0.5755794 ,  0.04805534,
         0.24434762,  0.55015785,  0.30462384, -0.76177585, -0.08158378]],
      dtype=float32)

In [12]:
tf.nn.softmax(predictions).numpy()

array([[0.10052302, 0.12185263, 0.1784503 , 0.04574242, 0.08534149,
        0.10385058, 0.14100046, 0.11030279, 0.03797126, 0.07496502]],
      dtype=float32)

In [13]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [14]:
loss_fn(y_train[:1], predictions).numpy()

2.2648022

In [15]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [16]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 9s 4ms/step - loss: 0.2918 - accuracy: 0.9157
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1409 - accuracy: 0.9582
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1079 - accuracy: 0.9672
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0890 - accuracy: 0.9727
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0755 - accuracy: 0.9769


In [17]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [18]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.7626980e-09, 2.5128580e-10, 2.3051071e-07, 1.0094094e-05,
        4.5744016e-12, 4.8912892e-09, 7.1687770e-15, 9.9998951e-01,
        6.4547168e-09, 6.2870996e-08],
       [6.0723022e-09, 1.7243107e-03, 9.9826860e-01, 6.8205604e-06,
        3.5475633e-15, 8.3498897e-08, 4.0648811e-08, 1.1507263e-11,
        1.2262605e-07, 1.2264811e-13],
       [4.8358341e-08, 9.9964178e-01, 2.4631085e-05, 5.4828602e-06,
        9.2449663e-06, 6.6215466e-07, 4.8606544e-06, 2.8320681e-04,
        2.8631801e-05, 1.4044965e-06],
       [9.9966395e-01, 1.5778340e-10, 9.0167094e-05, 2.9058350e-07,
        5.6929562e-06, 7.9165477e-07, 2.2092508e-04, 3.4224724e-06,
        2.1276083e-08, 1.4659206e-05],
       [1.8174736e-06, 6.0624776e-11, 1.0171253e-04, 1.8899952e-07,
        9.5597577e-01, 2.0990778e-06, 9.2656868e-05, 5.7413813e-06,
        2.9607754e-06, 4.3817103e-02]], dtype=float32)>